app:
  image: ibmcom/swift-ubuntu:3.1.1
  ports:
    - "8080:8080"
  volumes:
    - .:/Kitura-Starter
  command: bash -c "cd /Kitura-Starter && swift package clean && swift build && swift test && ./.build/debug/Kitura-Starter"
